### ISSUE TITLE
Add TDT BSM support

### ISSUE THREAD

**Issue by goblinmaks** [patman15/BMS_BLE-HA#102]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate of any [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Please describe the enhancement you would like to have.

```text
https://www.tdtbms.com/products-category/smart-bms.html
```

### Additional context

https://www.tdtbms.com/products-category/smart-bms.html
https://www.tdtbms.com/download.html

AndroidApp https://www.tdtbms.com/download-category/bluetooth-app.html

**Comment by patman15** [comment]
It [looks as](https://github.com/syssi/esphome-seplos-bms/issues/71) if the TDT BMS uses a similar protocol to the Seplos v2.0. Thus, I will first try to finish #101 and then come back to your request. Maybe it's solved with one implementation.
Meanwhile, please provide the output of `bluetoothctl info <MAC>` and the [service explorer script](https://github.com/hbldh/bleak/blob/develop/examples/service_explorer.py).

**Comment by goblinmaks** [comment]
Yep, looks itbvery similar if compare it by rs-485 part. I hope it will be similar for bluetooth proto.

**Comment by goblinmaks** [comment]
![image](https://github.com/user-attachments/assets/498ca4eb-2e8b-4b5d-9281-f0c6b39afe09)
![image](https://github.com/user-attachments/assets/0de425a9-497a-4047-be4e-0a8032d808d5)

**Comment by patman15** [comment]
Hi @goblinmaks, just checking, still interested? I would have soon time to try an implementation ...

**Comment by goblinmaks** [comment]
Still intereting, I will support with all that I can.

**Comment by patman15** [comment]
Hey! I started to look at what the BT app does, but for me it looks not really similar to a Seplos v2 BMS, but maybe I'm to tired. Are you able to to [capture the Bluetooth traffic](https://www.caichinger.com/blog/2020/11/08/capture_bluetooth_traffic_from_android/) when using the app with the battery? That would be the simplest way for me to get it running.

**Comment by goblinmaks** [comment]
Captured
[btsnoop_hci.log](https://github.com/user-attachments/files/18115472/btsnoop_hci.log)

**Comment by patman15** [comment]
Excellent, thanks. Confirms my thoughts, but now I have some real data I can implement against, great!

**Comment by patman15** [comment]
@goblinmaks first version available on the branch. If you can provide me a debug log and check values against the app, it would be great.

**Comment by goblinmaks** [comment]
Super, I will do it tomorrow. Also I missed to add screnshoy from app when capture bluetooth traffic. ![Screenshot_20241212_193215_BMS Meta.jpg](https://github.com/user-attachments/assets/789ac846-7ac1-4c4f-b39e-880ec1d4957f)

**Comment by goblinmaks** [comment]
![image](https://github.com/user-attachments/assets/52afa1c0-775d-4f24-8339-88100367a889)
Could you please share more info how to debug it ?

**Comment by patman15** [comment]
Please have a look at the troubleshooting section of the README. I can help more later today. Most interesting is the output of `bluetoothctl info <MAC>`

**Comment by goblinmaks** [comment]
![image](https://github.com/user-attachments/assets/5b4af7c7-9537-4f55-9409-75a876e809cc)

**Comment by goblinmaks** [comment]
ok, i have changed local name pattern to part of mac like "C0-D6*" and remove matching by id. Have some connecting progress 
![image](https://github.com/user-attachments/assets/1c9ddd27-d694-423a-a12f-d2f661cea2c0)

**Comment by patman15** [comment]
Ok, for some reason the device changes it's name. Which is strange. Can you provide me the `raw advertisement` info using [nRF connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) and try the updated version I just pushed?

**Comment by goblinmaks** [comment]
![image](https://github.com/user-attachments/assets/a178c06f-9fe9-4b72-9aef-2787abad8a06)
Automatically detects with latest changes, but not received any values.

**Comment by patman15** [comment]
Did you check if you need to pair the device, i.e. `bluetoothctl pair <MAC>`? Note that this does not work with a proxy!

**Comment by patman15** [comment]
@goblinmaks I checked your recording and saw that there is an enable code. I added it, can you try again?

**Comment by goblinmaks** [comment]
ok, will try it now.

**Comment by goblinmaks** [comment]
@patman15 Excellent!
Works correctly using bluetooth_proxy and correctly get initial data. 
Let me leave it for few hours to check long data collection. 



![image](https://github.com/user-attachments/assets/90e9c5bd-3897-42c2-95b8-dff9ddf5f4b3)
![image](https://github.com/user-attachments/assets/60fb80cf-e471-42df-b812-2cad2bece680)

**Comment by goblinmaks** [comment]
Looks good after few working hours and few reboots of bluetooth proxy and HA. 

Thank you very much for your work.

**Comment by andreitoma-github** [comment]
Hi @patman15 !
Few weeks ago I used a Win10 machine and made a Wireshark capture between the Meta BMS (running on iPhone) and the a  WattCycle battery (12V, 100Ah with BT).
The BMS advertise the name XDZN_001_AC50 and I suspect that is a TDT BMS for 4 cells only.
I hope this capture will be useful for you to validate the new TDT BSM support feature.
[Capture1_connect_get_data_few_seconds_disconnect.zip](https://github.com/user-attachments/files/18146091/Capture1_connect_get_data_few_seconds_disconnect.zip)

**Comment by goblinmaks** [comment]
@andreitoma-github right not this integration works but have some problem with initial connection. I suspect that it can be a problem with my local setup only. Could you please try to install integration from the branch and check with your battery ?

**Comment by patman15** [comment]
> Ok, have some error when re-add integration
> 
Looks like your device was not correctly discovered, i.e. it has not announced the name via Bluetooth. That raises the error.

**Comment by patman15** [comment]
> Hi @patman15 ! Few weeks ago I used a Win10 machine and made a Wireshark capture between the Meta BMS (running on iPhone) and the a WattCycle battery (12V, 100Ah with BT). The BMS advertise the name XDZN_001_AC50 and I suspect that is a TDT BMS for 4 cells only. I hope this capture will be useful for you to validate the new TDT BSM support feature.

Hi @andreitoma-github! Thanks for the input. The issue is that the current implementation can only handle 16 cell batteries since I did not exactly know how the responses would look like for a different cell count. Thanks to you I now know, I can fix that quite easily.

**Comment by patman15** [comment]
@andreitoma-github fixed 4S version, @goblinmaks there was something wrong with yesterdays version. Tests did not pass, probably try again with current one.

**Comment by goblinmaks** [comment]
@patman15 re-adding works good with adapter. Some problem with bluetooth_proxy

**Comment by andreitoma-github** [comment]
Hi @patman15 
The commit 0d29712c7d3f3520ab267812f7650bc2af8c0410 on '102-add-tdt-bsm-support' branch works  for me. 
All sensors look correct. 
The cell voltages and cell temperatures are correct. 
The BT connection gets disrupted when the phone app is open and fetches data, but the integration reconnects after phone app is closed. 
Thank you!
![XDZN_001_AC50_HomeAssistant_BMS_16Dec2024](https://github.com/user-attachments/assets/c51e5f9a-3926-4c17-867e-d116024941d1)
![XDZN_001_AC50_Meta_BMS_16Dec2024](https://github.com/user-attachments/assets/3ec61c97-c13b-45d6-a18a-3a4e0a39cf01)

**Comment by patman15** [comment]
@andreitoma-github thanks for the feedback, will soon merge the code and include it with the next release.
