### ISSUE TITLE
Displayed battery temperature too high.

### ISSUE THREAD

**Issue by Alex-DeIt** [patman15/BMS_BLE-HA#126]
### Checklist

- [X] I have tried the latest version of BMS_BLE-HA.
- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issue](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3Abug).
- [X] I have filled out the issue template to the best of my ability.

### Provide the type of BMS you used:

Creabest, LiFePO4 200Ah

### Describe the issue

The displayed battery temperature is slightly too high.
![image](https://github.com/user-attachments/assets/f47bbc72-bce1-4b19-be4c-5fc55147b1b6)

### Reproduction steps

```text
1.
2.
3.
...
```

### Debug logs

[home-assistant.log](https://github.com/user-attachments/files/18251177/home-assistant.log)

**Comment by patman15** [comment]
Thanks, good catch, confirmed bug. BMS sends unexpected response that is not filtered.

**Comment by Alex-DeIt** [comment]
Hello Patrick,
yes , it is quite possible. The external thermometer of my motorhome displays approximately -1.5°C and the thermometer in the trunk (close to the battery compartment) approximatley -1°C.
