### ISSUE TITLE
Gas level sensor

### ISSUE THREAD

**Issue by 7wells** [patman15/BMS_BLE-HA#36]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate of any [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hello! 

Understanding that this is indeed about battery management systems (BMS) and not about gas level sensors (I should not have ticked the 2nd tick box 🫢), I hope that my question here does not annoy you. If it does, please kindly delete my post and forgive me.

My question is if you think it is possible to hook into a Bluetooth gas level sensor like from Truma or Mopeka? I have one from Truma, and there does not seem to be any HA integration for it. I can read the level (in % and kg gas) with Truma's native Android app ("Level Control"), and I can see the sensor (attached to the bottom of the gas bottle) via the Android app "nRF Connect", which is a very powerful tool regarding BLE (incl. server mode), but its possibilities are way beyond my capabilities, I'm afraid.

### Describe the solution you'd like

If you see a way how I could dig deeper into this, I would welcome your hints pointing me into the right direction.

Please accept my apologies that this is not really a feature request. I posted this here, because I was not sure how else I could ask you. And you seem to know already a lot about BLE. 👍

**Comment by patman15** [comment]
Hi!
Well if there is an app and a visibility in *nRF Connect* it shouldn't be too hard to get it integrated. Depending on the structure of the device (passive or active connections) you probably are better off with [ble_monitor](https://github.com/custom-components/ble_monitor).
Can you post raw data of the advertisement button *raw* on the first screen and if you can connect to the device the information about the characteristics? Then I can give you some hints. Spoiler: I can't do another integration I'm already working on a second one and maintenance will kill me.
