### ISSUE TITLE
Multiple JK BMS as single device

### ISSUE THREAD

**Issue by RoySalisbury** [patman15/BMS_BLE-HA#62]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate of any [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When adding multiple JK BMS devices, they are all combined into a single device and not individual devices.

### Describe the solution you'd like

This seems like an isue that was reported before and fixed for another BMS (#30).  But even later versions still group everything under the name.  I have 8 JK BMS devices, so its a bit of a problem.

**Comment by patman15** [comment]
Hi! Thanks for reporting! That's weird #30 should have fixed it for all BMS. Can you share a screenshot of the issue you see and share the relevant parts of `/config/.storage/core.entity_registry` and `/config/.storage/core.device_registry`? Relevant in this case means all entries that contain` bms_ble`.
Thanks a lot!

**Comment by RoySalisbury** [comment]
I'll try to set it up again and send you the requested data.  I wrote my own BLE to mqtt publisher that I run outside of HA (one instance per BMS).  So I was just trying to "consolidate".  I'll disable mine for a few minutes and let this one auto setup again.

**Comment by patman15** [comment]
Thanks a lot,  could you provide also a Homeassistant log in debug settings? That would be awesome.

**Comment by patman15** [comment]
@RoySalisbury found the issue, thanks for the hint. Can you check the [branch](https://github.com/patman15/BMS_BLE-HA/tree/62-multiple-jk-bms-as-single-device) before I release?
