### ISSUE TITLE
Bluetooth BLE security JBD, Daly, JK

### ISSUE THREAD

**Issue by Massimo-B** [patman15/BMS_BLE-HA#86]
### Checklist

- [X] I need support with using the integration.
- [X] My issue is not a [feature request](https://github.com/patman15/BMS_BLE-HA/issues/new?assignees=&labels=Feature%2BRequest&projects=&template=feature_request.yml)
- [x] I'm not avoiding to fill out the [bug report](https://github.com/patman15/BMS_BLE-HA/issues/new?assignees=&labels=Bug&projects=&template=bug.yml) form.

### Describe the issue

Hi,

please excuse my off-topic request. As you have knowledge about the BLE interfaces of most common chinese BMS manufacturers like JBD, Daly and JK I would like to discuss:
I found that all of these BLE interfaces are entirely insecure. Everyone without physical access is able to connect. Do you have any idea if it is possible to add some security if not adding power on/off switches into the Bluetooth dongle wiring?
I found that for instance the BT transceivers in Daly BMS are USB-based. Isn't it possible to replace by other transceivers with real BT pairing? On combined BT/Wifi transceivers in Daly it is currently  not possible to disabled the insecure BT.
On JBD I found reports about replacing the Bluetooth transceiver with a HM10 module, that first must be programmed via USB-TTL converter to enable encrypted connection using AT commands.

I would like to use your solution on a motorhome with Homeassistant. Insecure access to wireless interfaces is not acceptable when going mobile.

**Comment by patman15** [comment]
You are absolutely right, the access to the BMSs are totally insecure, i.e. it took me less than a few minutes to overcome. The only device in this area that I couldn't easily work around, was a Victron SmartSolar charger. Probably, (I do not know) also their batteries are reasonably secured.

I have no experience with any hardware modifications, so unfortunately I cannot help you here, except that if you modify something, e.g. different BT adapter with encryption/authentication, I can help you get it integrated again.

The integration itself, support everything Bluetooth supports, mostly limited by the BT implementation of the BMS. So if the BMS would support BT keys, pairing, the integration would still work seamlessly.

Best regards, Patrick
